FROM archlinux:latest

WORKDIR /app

COPY requirements.txt .
COPY install.sh .

RUN printf '#!/bin/sh\n"$@"' > /usr/bin/sudo && chmod +x /usr/bin/sudo

RUN chmod +x script.sh && bash script.sh

COPY cof.py .

CMD ["/bin/bash", "-c", "source env/bin/activate && python3 cofb.py"]

